CREATE TABLE `configuracoes_laudo` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`nomeClinica` varchar(256),
	`enderecoClinica` text,
	`telefoneClinica` varchar(20),
	`emailClinica` varchar(320),
	`cnpjClinica` varchar(18),
	`logotipoUrl` text,
	`nomeProfissional` varchar(256),
	`titulosProfissional` varchar(256),
	`crfa` varchar(32),
	`assinaturaUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `configuracoes_laudo_id` PRIMARY KEY(`id`),
	CONSTRAINT `configuracoes_laudo_userId_unique` UNIQUE(`userId`)
);
--> statement-breakpoint
CREATE TABLE `exames_audiometricos` (
	`id` int AUTO_INCREMENT NOT NULL,
	`colaboradorId` int NOT NULL,
	`empresaId` int NOT NULL,
	`userId` int NOT NULL,
	`audiometro` varchar(128),
	`dataCalibracaoAudiometro` varchar(10),
	`dataRealizacao` varchar(10) NOT NULL,
	`motivoAvaliacao` enum('admissional','periodico','retorno_trabalho','demissional','mudanca_riscos','monitoracao_pontual','consulta_medica') NOT NULL DEFAULT 'admissional',
	`repousoAuditivo` enum('maior_igual_14h','menor_14h','nao_informado') DEFAULT 'nao_informado',
	`repousoHoras` varchar(10),
	`queixa` boolean DEFAULT false,
	`queixaDescricao` text,
	`epiUso` enum('nao','sim','plug','concha') DEFAULT 'nao',
	`meatoscopiaOD` enum('normal','obstrucao_parcial','obstrucao_total') DEFAULT 'normal',
	`meatoscopiaOE` enum('normal','obstrucao_parcial','obstrucao_total') DEFAULT 'normal',
	`vaOD250` int,
	`vaOD500` int,
	`vaOD1000` int,
	`vaOD2000` int,
	`vaOD3000` int,
	`vaOD4000` int,
	`vaOD6000` int,
	`vaOD8000` int,
	`vaMascOD250` int,
	`vaMascOD500` int,
	`vaMascOD1000` int,
	`vaMascOD2000` int,
	`vaMascOD3000` int,
	`vaMascOD4000` int,
	`vaMascOD6000` int,
	`vaMascOD8000` int,
	`vaTipoOD250` varchar(20),
	`vaTipoOD500` varchar(20),
	`vaTipoOD1000` varchar(20),
	`vaTipoOD2000` varchar(20),
	`vaTipoOD3000` varchar(20),
	`vaTipoOD4000` varchar(20),
	`vaTipoOD6000` varchar(20),
	`vaTipoOD8000` varchar(20),
	`vaOE250` int,
	`vaOE500` int,
	`vaOE1000` int,
	`vaOE2000` int,
	`vaOE3000` int,
	`vaOE4000` int,
	`vaOE6000` int,
	`vaOE8000` int,
	`vaMascOE250` int,
	`vaMascOE500` int,
	`vaMascOE1000` int,
	`vaMascOE2000` int,
	`vaMascOE3000` int,
	`vaMascOE4000` int,
	`vaMascOE6000` int,
	`vaMascOE8000` int,
	`vaTipoOE250` varchar(20),
	`vaTipoOE500` varchar(20),
	`vaTipoOE1000` varchar(20),
	`vaTipoOE2000` varchar(20),
	`vaTipoOE3000` varchar(20),
	`vaTipoOE4000` varchar(20),
	`vaTipoOE6000` varchar(20),
	`vaTipoOE8000` varchar(20),
	`voOD500` int,
	`voOD1000` int,
	`voOD2000` int,
	`voOD3000` int,
	`voOD4000` int,
	`voMascOD500` int,
	`voMascOD1000` int,
	`voMascOD2000` int,
	`voMascOD3000` int,
	`voMascOD4000` int,
	`voTipoOD500` varchar(20),
	`voTipoOD1000` varchar(20),
	`voTipoOD2000` varchar(20),
	`voTipoOD3000` varchar(20),
	`voTipoOD4000` varchar(20),
	`voOE500` int,
	`voOE1000` int,
	`voOE2000` int,
	`voOE3000` int,
	`voOE4000` int,
	`voMascOE500` int,
	`voMascOE1000` int,
	`voMascOE2000` int,
	`voMascOE3000` int,
	`voMascOE4000` int,
	`voTipoOE500` varchar(20),
	`voTipoOE1000` varchar(20),
	`voTipoOE2000` varchar(20),
	`voTipoOE3000` varchar(20),
	`voTipoOE4000` varchar(20),
	`mediaOD` decimal(5,2),
	`mediaOE` decimal(5,2),
	`metodoMedia` varchar(64),
	`tipoMedia` enum('tritonal','quadritonal'),
	`classificacaoOD` varchar(128),
	`classificacaoOE` varchar(128),
	`lrfOD` int,
	`ldvOD` int,
	`mascOD` int,
	`lrfOE` int,
	`ldvOE` int,
	`mascOE` int,
	`irfIntensidadeOD` int,
	`irfMonossilabosOD` int,
	`irfDissilabosOD` int,
	`irfMascOD` int,
	`irfIntensidadeOE` int,
	`irfMonossilabosOE` int,
	`irfDissilabosOE` int,
	`irfMascOE` int,
	`mascVAMinOD` int,
	`mascVAMaxOD` int,
	`mascVOMinOD` int,
	`mascVOMaxOD` int,
	`mascVAMinOE` int,
	`mascVAMaxOE` int,
	`mascVOMinOE` int,
	`mascVOMaxOE` int,
	`parecerAudiologico` text,
	`resultado` enum('normal','alteracao_leve','alteracao_moderada','alteracao_severa','alteracao_profunda') DEFAULT 'normal',
	`status` enum('rascunho','finalizado','laudo_emitido') NOT NULL DEFAULT 'rascunho',
	`laudoUrl` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `exames_audiometricos_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `pareceres_modelo` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`titulo` varchar(256) NOT NULL,
	`texto` text NOT NULL,
	`categoria` varchar(128),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `pareceres_modelo_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `colaboradores` ADD `sexo` enum('M','F','outro');--> statement-breakpoint
ALTER TABLE `empresas` ADD `logotipoUrl` text;--> statement-breakpoint
ALTER TABLE `empresas` ADD `cep` varchar(10);--> statement-breakpoint
ALTER TABLE `empresas` ADD `cidade` varchar(128);--> statement-breakpoint
ALTER TABLE `empresas` ADD `estado` varchar(2);--> statement-breakpoint
ALTER TABLE `exames` ADD `exameAudiometricoId` int;--> statement-breakpoint
ALTER TABLE `users` ADD `nomeCompleto` varchar(256);--> statement-breakpoint
ALTER TABLE `users` ADD `tituloLaudo` varchar(256);--> statement-breakpoint
ALTER TABLE `users` ADD `assinaturaUrl` text;